# Generated by Django 4.2.16 on 2024-09-17 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotCategories',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('categoryName', models.CharField(max_length=50, unique=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'IOT Category',
                'verbose_name_plural': 'IOT Categories',
            },
        ),
        migrations.CreateModel(
            name='IotDevices',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deviceId', models.CharField(max_length=100)),
                ('deviceName', models.CharField(max_length=100)),
                ('deviceLabel', models.CharField(blank=True, max_length=100, null=True)),
                ('deviceResponse', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('deviceCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_device', to='infrastructure.iotcategories')),
            ],
            options={
                'verbose_name': 'IOT Device',
                'verbose_name_plural': 'IOT Devices',
            },
        ),
        migrations.CreateModel(
            name='ThermostatSensor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pm_ten', models.CharField(blank=True, max_length=100, null=True)),
                ('pm_two_five', models.CharField(blank=True, max_length=100, null=True)),
                ('noise', models.CharField(blank=True, max_length=100, null=True)),
                ('co_two', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=100, null=True)),
                ('fs', models.CharField(blank=True, max_length=100, null=True)),
                ('mac', models.CharField(blank=True, max_length=100, null=True)),
                ('hum', models.CharField(blank=True, max_length=100, null=True)),
                ('voc', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('lux', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.CharField(blank=True, max_length=100, null=True)),
                ('hv', models.CharField(blank=True, max_length=100, null=True)),
                ('t_sen', models.CharField(blank=True, max_length=100, null=True)),
                ('s_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('c_h', models.CharField(blank=True, max_length=100, null=True)),
                ('occ', models.CharField(blank=True, max_length=100, null=True)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
                ('room_number', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('thermostate_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thermostat_sensor_data', to='infrastructure.iotdevices')),
            ],
            options={
                'verbose_name': 'Thermostat Sensor',
                'verbose_name_plural': 'Thermostat Sensors',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=35)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.AddField(
            model_name='iotdevices',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_device', to='infrastructure.location'),
        ),
        migrations.AddField(
            model_name='iotdevices',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
    ]
