# Generated by Django 4.2.16 on 2025-02-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotcategories',
            name='categoryName',
            field=models.CharField(max_length=50),
        ),
    ]
