# Generated by Django 4.2.16 on 2025-06-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_iotcategories_categoryname'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevices',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
