# Generated by Django 4.2.16 on 2024-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iotconfig',
            options={'verbose_name': 'IOT Config', 'verbose_name_plural': 'IOT Configs'},
        ),
        migrations.AddField(
            model_name='iotconfig',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='iotconfig',
            name='token',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
